FPS = 10
WINDOW_SIZE = (600,600)
BACKGROUND = (150,90,30)
BLACK = (0,0,0)
WHITE = (255,255,255)
GREY = (180,180,180)
MIDGREY = (90,90,90)
YELLOW = (255,255,0)
ACTIVE_CELL_COLOR = (50,111,237,75)
INPUT_FONT_COLOR = (100,240,50)
INPUT_SIZE = 40
CELL_QTY = 8
CELL_SIZE = 60
COLORS = ["black_cell.png","white_cell.png"]
#COLORS = [BLACK,WHITE]
FNT_NAME = 'arial'
FNT_SIZE = 18
LTRS = "abcdefgh"
IMG_PATH = "assets/images/"
WIN_BG_IMG = "backwindow.jpg"
BOARD_BG_IMG = "backboard.jpg"
PIECE_PATH = 'assets/images/pieces/'
PIECES_TYPES = {
    'k': ('King','b'), 'K':('King','w'),
    'q': ('Queen','b'), 'Q':('Queen','w'),
    'r': ('Rook','b'), 'R':('Rook','w'),
    'b': ('Bishop','b'), 'B':('Bishop','w'),
    'n': ('Knight','b'), 'N':('Knight','w'),
    'p': ('Pawn','b'), 'P':('Pawn','w')
}

P_COLOR = "w"
MAX_DEPTH = 3
